approvedGitRepositories:
  - "**"

enableScripts: false

nodeLinker: node-modules

npmAuditIgnoreAdvisories:
  - 1113517
  - 1113686

npmMinimalAgeGate: 4320

npmPreapprovedPackages:
  - outline-icons
