# ---------------------------------------------------------------------------
# Static assets bucket — built Vite JS/CSS, fonts, images
# Served via CloudFront with OAC. No public access.
# ---------------------------------------------------------------------------
resource "aws_s3_bucket" "static" {
  bucket = "${var.project}-${var.env}-static-assets"
  tags   = { Name = "${var.project}-${var.env}-static-assets", Purpose = "static" }
}

resource "aws_s3_bucket_public_access_block" "static" {
  bucket                  = aws_s3_bucket.static.id
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

resource "aws_s3_bucket_versioning" "static" {
  bucket = aws_s3_bucket.static.id
  versioning_configuration { status = "Enabled" }
}

# ---------------------------------------------------------------------------
# Uploads bucket — user files, avatars, exports, imports
# Accessed via presigned URLs generated by the Web API and Worker.
# ---------------------------------------------------------------------------
resource "aws_s3_bucket" "uploads" {
  bucket = "${var.project}-${var.env}-uploads"
  tags   = { Name = "${var.project}-${var.env}-uploads", Purpose = "uploads" }
}

resource "aws_s3_bucket_public_access_block" "uploads" {
  bucket                  = aws_s3_bucket.uploads.id
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

resource "aws_s3_bucket_versioning" "uploads" {
  bucket = aws_s3_bucket.uploads.id
  versioning_configuration { status = "Enabled" }
}

resource "aws_s3_bucket_cors_configuration" "uploads" {
  bucket = aws_s3_bucket.uploads.id

  cors_rule {
    allowed_headers = ["*"]
    allowed_methods = ["GET", "PUT", "POST", "DELETE", "HEAD"]
    allowed_origins = var.uploads_cors_origins
    expose_headers  = ["ETag"]
    max_age_seconds = 3000
  }
}

resource "aws_s3_bucket_lifecycle_configuration" "uploads" {
  bucket = aws_s3_bucket.uploads.id

  rule {
    id     = "abort-incomplete-multipart"
    status = "Enabled"
    abort_incomplete_multipart_upload { days_after_initiation = 7 }
  }
}
